packages:
  - "packages/**"
  - "examples/*"
  - "experiments/devtools-proto"
  - "!**/node_modules/**"

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.22
  vite-plus: latest
  binaryen: ^129.0.0
  "@vitest/coverage-v8": ^4.1.7
  wavefile: ^11.0.0
  tsx: ^4.22.3
  "@vitejs/devtools-kit": ^0.2.0
  jszip: ^3.10.1
  playwright: ^1.60.0
  "@vitest/browser": ^4.1.7
  "@vitest/browser-playwright": ^4.1.7
  "@playwright/test": ^1.60.0
  "@vue-flow/core": ^1.48.2
  "@vue-flow/background": ^1.3.2
  "@vue-flow/controls": ^1.1.3
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  esbuild: true
  vue-demi: true
