// @unworklet/worklet — AudioWorklet-side template + helpers.
//
// Per docs/04-worklet-runtime.md and draft_spec §3.2 / §7.4. The actual
// per-processor AudioWorkletProcessor template is generated by the compiler's
// generateWorkletModule() function — that emitted code is fully self-contained
// and does not reference this package at runtime. This module re-exports the
// codegen function for callers that want to author worklet bundles manually.

export {
  generateWorkletModule,
  generateWorkletBundle,
  type WorkletModuleOptions,
  type WorkletBundle,
} from "@unworklet/compiler";

// Browser-side helper that ties everything together: compile, register the
// worklet module, instantiate the AudioWorkletNode, and surface the
// node-shaped object documented in docs/05-client §2.
export { createWasmNode, type WasmUnworkletNode, type CreateWasmNodeOptions } from "./createWasmNode.js";

// Snapshot-format bridge: convert an engine-format (UWS1) snapshot blob
// into a WASM-format (UWSN) blob suitable for `_handleRestore`. Used
// internally by createWasmNode.restore to ferry migrated state from a
// host-side JS Engine into the WASM worklet's linear memory. Exported so
// host integrators can drive the same conversion.
export { engineSnapshotToWasm } from "./snapshot-bridge.js";
