// @unworklet/worklet — AudioWorklet-side template + helpers.
//
// Per docs/04-worklet-runtime.md and draft_spec §3.2 / §7.4. The actual
// per-processor AudioWorkletProcessor template is generated by the compiler's
// generateWorkletModule() function — that emitted code is fully self-contained
// and does not reference this package at runtime. This module re-exports the
// codegen function for callers that want to author worklet bundles manually.

export {
  generateWorkletModule,
  generateWorkletBundle,
  type WorkletModuleOptions,
  type WorkletBundle,
} from "@unworklet/compiler";
